=== rstehwien/WTCC_W/src/xml/WildTalentsCharacterCreator.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="data">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element minOccurs="1" ref="character"/>
          <xs:element minOccurs="1" ref="tables"/>
          <xs:element ref="modifiers"/>
          <xs:element ref="pools"/>
          <xs:element ref="archetypes"/>
          <xs:element maxOccurs="1" minOccurs="1" ref="meta_qualities"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute form="unqualified" name="version" type="xs:integer" use="required"/>
      <xs:attribute name="cost_willpower" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="cost_willpower_base" type="xs:positiveInteger" use="required"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="character">
    <xs:complexType>
      <xs:sequence>
        <xs:choice maxOccurs="unbounded" minOccurs="0">
          <xs:element ref="infos" minOccurs="0"/>
          <xs:element ref="willpower" minOccurs="0"/>
          <xs:element ref="custom_modifiers" minOccurs="0"/>
          <xs:element maxOccurs="1" minOccurs="0" ref="pools"/>
          <xs:element minOccurs="0" ref="meta_qualities"/>
          <xs:element minOccurs="0" ref="measurements"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute form="unqualified" name="version" type="xs:integer" use="required"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="points_archetype" use="required" type="xs:integer"/>
      <xs:attribute name="points_powers" use="required" type="xs:nonNegativeInteger"/>
      <xs:attribute name="points_skills" use="required" type="xs:nonNegativeInteger"/>
      <xs:attribute name="points_stats" use="required" type="xs:nonNegativeInteger"/>
      <xs:attribute name="points_willpower" use="required" type="xs:nonNegativeInteger"/>
      <xs:attribute name="points" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="infos">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="info" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="info">
    <xs:complexType mixed="true">
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="willpower">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="motivation"/>
      </xs:sequence>
      <xs:attribute name="base" use="required" type="xs:nonNegativeInteger"/>
      <xs:attribute name="current" use="required" type="xs:nonNegativeInteger"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute default="0" name="points" type="xs:nonNegativeInteger"/>
      <xs:attribute default="0" name="min_base" type="xs:nonNegativeInteger"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="motivation">
    <xs:complexType>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="value" use="required" type="xs:nonNegativeInteger"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="custom_modifiers">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="effect" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="ref" type="xs:NCName" use="optional"/>
      <xs:attribute name="name" type="xs:string" use="optional"/>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="effect">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="modifier"/>
      </xs:sequence>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="cost" type="xs:nonNegativeInteger" default="0"/>
      <xs:attribute name="is_add_measurement" type="xs:boolean" default="false"/>
      <xs:attribute name="note" type="xs:string"/>
      <xs:attribute name="is_note_required" type="xs:boolean" default="false"/>
      <xs:attribute name="link" type="xs:NCName"/>
      <xs:attribute default="false" name="is_link_required" type="xs:boolean"/>
      <xs:attribute name="source" type="xs:string"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute default="0" name="die_cost" type="xs:nonNegativeInteger"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="pools">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="pool"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute default="0" name="points" type="xs:nonNegativeInteger"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="pool">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="effect"/>
      </xs:sequence>
      <xs:attribute name="source" type="xs:string"/>
      <xs:attribute name="die_cost" type="xs:nonNegativeInteger" default="0"/>
      <xs:attribute name="hard" type="xs:nonNegativeInteger" default="0"/>
      <xs:attribute name="normal" type="xs:nonNegativeInteger" default="0"/>
      <xs:attribute name="type" type="xs:NCName" use="required"/>
      <xs:attribute name="wiggle" type="xs:nonNegativeInteger" default="0"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute default="0" name="points" type="xs:nonNegativeInteger"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="modifiers">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="modifier"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="modifier">
    <xs:complexType>
      <xs:attribute name="source" type="xs:string"/>
      <xs:attribute name="cost" use="required" type="xs:integer"/>
      <xs:attribute name="note" type="xs:string"/>
      <xs:attribute name="is_note_required" type="xs:boolean" default="false"/>
      <xs:attribute name="has_ranks" type="xs:boolean" default="false"/>
      <xs:attribute name="ranks" type="xs:positiveInteger" default="1"/>
      <xs:attribute name="type" use="required" type="xs:string"/>
      <xs:attribute name="link" type="xs:NCName"/>
      <xs:attribute default="false" name="is_link_required" type="xs:boolean"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="mod" type="xs:integer" use="optional" default="0"/>
      <xs:attribute default="false" name="is_chosen" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="meta_qualities">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="meta_quality"/>
      </xs:sequence>
      <xs:attribute name="points" type="xs:integer" default="0"/>
      <xs:attribute name="source" type="xs:string"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="type" type="xs:NCName" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="meta_quality">
    <xs:complexType>
      <xs:attribute name="source" type="xs:string"/>
      <xs:attribute name="cost" type="xs:integer" use="required"/>
      <xs:attribute name="is_custom" type="xs:boolean" default="false"/>
      <xs:attribute name="note" type="xs:string"/>
      <xs:attribute name="is_note_required" type="xs:boolean" default="false"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string" use="required"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="type" type="xs:NCName" use="required"/>
      <xs:attribute default="true" name="is_chosen" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="tables">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="table" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="table">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="measurement" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="beyond" type="xs:decimal"/>
      <xs:attribute name="boost" type="xs:decimal"/>
      <xs:attribute name="type" type="xs:NCName"/>
      <xs:attribute name="units" type="xs:string"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="link" type="xs:NCName" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="measurement">
    <xs:complexType>
      <xs:attribute name="type" type="xs:NCName"/>
      <xs:attribute name="pool" use="required" type="xs:nonNegativeInteger"/>
      <xs:attribute name="text" type="xs:string"/>
      <xs:attribute name="units" type="xs:string"/>
      <xs:attribute name="value" type="xs:decimal"/>
      <xs:attribute name="text_cols" type="xs:string"/>
      <xs:attribute name="ref" type="xs:NCName"/>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="id" type="xs:ID"/>
      <xs:attribute name="link" type="xs:NCName" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="archetypes">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="meta_qualities"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="measurements">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="measurement"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rstehwien/WTCC_W/src/xml/WildTalentsCharacterCreatorData.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="WildTalentsCharacterCreator.xsd" version="1" cost_willpower="1" cost_willpower_base="3">
  <!-- 
    Notes 
    * all elements have a
      * id _ unique identifier, optional
      * ref_ reference for lookups, can have duplicates, optional
      * name _ display name, optional
    * ref or id used when linking elements together
    * cost for stats and skills doesn't include Native modifier 
  -->
  <pools>
    <!--
        Stats
      -->
    <pool type="stat" name="Body">
      <effect type="stat" name="Body" ref="body" cost="4"/>
    </pool>
    <pool type="stat" name="Coordination">
      <effect type="stat" name="Coordination" ref="coordination" cost="4"/>
    </pool>
    <pool type="stat" name="Sense">
      <effect type="stat" name="Sense" ref="sense" cost="4"/>
    </pool>
    <pool type="stat" name="Mind">
      <effect type="stat" name="Mind" ref="mind" cost="4"/>
    </pool>
    <pool type="stat" name="Charm">
      <effect type="stat" name="Charm" ref="charm" cost="4"/>
    </pool>
    <pool type="stat" name="Command">
      <effect type="stat" name="Command" ref="command" cost="4"/>
    </pool>
    <!--
        Skills, starting with custom ones
      -->
    <pool type="skill" name="Custom Standard Skill">
      <effect type="skill" cost="1" name="Custom Standard Skill" source="WT2E"/>
    </pool>
    <pool type="skill" name="Custom Build Skill">
      <effect type="skill" cost="0" name="Custom Build Skill" source="WT2E"/>
    </pool>
    <!-- Wild Talent Skills -->
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Athletics" link="body" is_note_required="true" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Block" link="body" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Brawling" link="body" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Endurance" link="body" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Melee Weapon" link="body" is_note_required="true" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Dodge" link="coordination" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Driving" link="coordination" is_note_required="true" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Ranged Weapon" link="coordination" is_note_required="true" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Stealth" link="coordination" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Empathy" link="sense" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Perception" link="sense" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Scrutiny" link="sense" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="First Aid" link="mind" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Knowledge" link="mind" is_note_required="true" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Language" link="mind" is_note_required="true" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Medicine" link="mind" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Navigation" link="mind" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Research" link="mind" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Security Systems" link="mind" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Streetwise" link="mind" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Survival" link="mind" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Tatics" link="mind" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Lie" link="charm" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Performance" link="charm" is_note_required="true" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Persuasion" link="charm" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Interrogation" link="command" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Intimidation" link="command" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Leadership" link="command" source="WT2E"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="1" name="Stability" link="command" source="WT2E"/>
    </pool>
    <!-- Basic Skills KC -->
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Boxing" link="body" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Lifting" link="body" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Running" link="body" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Sports" link="body" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Wrestling" link="body" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Acrobatics" link="coordination" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Archery" link="coordination" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Climb" link="coordination" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Dodge" link="coordination" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Evasion" link="coordination" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Horsemanship" link="coordination" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Pistol" link="coordination" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Rifle" link="coordination" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Empathy" link="sense" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Hear" link="sense" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Notice" link="sense" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Reflexes" link="sense" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Search" link="sense" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="See" link="sense" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Smell" link="sense" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Taste" link="sense" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Touch" link="sense" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Track" link="sense" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="A Single Academic Field" link="mind" is_note_required="true" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="A Language" link="mind" is_note_required="true" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Act" link="command" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Intimidate" link="command" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Lie" link="command" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Stability" link="command" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Bluff" link="charm" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Feign" link="charm" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Innocence" link="charm" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Lie" link="charm" source="KC"/>
    </pool>
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Seduce" link="charm" source="KC"/>
    </pool>
    <!-- Advanced Skills KC -->
    <pool type="skill" name="">
      <effect type="skill" cost="0" name="Athletics" link="body" source="KC">
        <modifier type="skill" name="Broad" cost="1"/>
      </effect>
    </pool>
